# Generated by Django 4.2.4 on 2023-08-31 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_img_para_id_alter_para_id_alter_text_para_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="name",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="head_img",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="ip",
        ),
    ]
