# Generated by Django 4.2.4 on 2023-09-01 04:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_name_comment_user_remove_comment_head_img_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="comment_users",
            new_name="hot",
        ),
    ]
