# Generated by Django 4.2.4 on 2023-09-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_rename_comment_users_blog_hot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blog",
            name="hot",
            field=models.IntegerField(default=0),
        ),
    ]
