# Generated by Django 4.2.4 on 2023-09-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_blog_comment_count_alter_blog_hot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="hot",
            field=models.IntegerField(),
        ),
    ]
