# Generated by Django 4.2.4 on 2023-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_blog_hot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="img_para",
            name="img_link",
        ),
        migrations.AddField(
            model_name="img_para",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
